### ISSUE TITLE
HTX: build fails with libcxl dependency on RHEL 7 BE on Power7 machine

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/HTX#107]
make[2]: Entering directory `/root/pridhiviraj/HTX-master/bin/hxecapi'
cc -D__HTX_LINUX__ -DTRUE=1 -DFALSE=0 -D__64BIT__ -D__HTX_LE__ -D__RELGR2600__ -I./ -I/usr/include/ -I/root/pridhiviraj/HTX-master//export/ppc64le//include/ -c memcopy.c -o memcopy.o
In file included from memcopy.c:20:0:
./memcopy.h:30:20: fatal error: libcxl.h: No such file or directory
 #include <libcxl.h>
                    ^
compilation terminated.
make[2]: *** [memcopy.o] Error 1
make[2]: Leaving directory `/root/pridhiviraj/HTX-master/bin/hxecapi'
make[1]: *** [hxecapi] Error 2
make[1]: Leaving directory `/root/pridhiviraj/HTX-master/bin'
make: *** [bin] Error 2
[root@jupiter6-lp2 HTX-master]# uname -a
Linux jupiter6-lp2.aus.stglabs.ibm.com 3.10.0-514.el7.ppc64 #1 SMP Wed Oct 19 11:30:41 EDT 2016 ppc64 ppc64 ppc64 GNU/Linux
[root@jupiter6-lp2 HTX-master]# lscpu 
Architecture:          ppc64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Big Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    4
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          2
Model:                 2.1 (pvr 004a 0201)
Model name:            POWER7 (architected), altivec supported
L1d cache:             32K
L1i cache:             32K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):

**Comment by manishmukul** [comment]
All the required dependencies are mentioned in README.md. 
https://github.com/open-power/HTX/blob/master/README.md

Please follow the steps provided there (with appropriate package-manager replacement for ubuntu<->rhel)

**Comment by pridhiviraj** [comment]
Hi i followed the required steps to keep the libcxl.so in /lib64/power7/ folder.
ls /lib64/power7/
libcxl.so  libcxl.so.1  power8

I have copied libcxl.so file to /lib64/power7/  folder.	
But still it is failing with above error

**Comment by dougmill-ibm** [comment]
I think you need the *development* libraries for CXL. Usually something like "libcxl-devel" or "libcxl-dev" depending on the distro.,

**Comment by ping678** [comment]
I got a problem when compile and install HTX uner RHEL7.3 on a P8 platform. After finishing the installation, there is no htx command.
Steps:
1. git clone https://www.github.com/open-power/HTX
2. cd HTX
3. yum install ncurses-libs.ppc64le ncurses-devel.ppc64le dapl-devel.ppc64le libcxl.ppc64le
4. modfify htx.mk, changed the 2 lines:
    HTX_RELEASE="htxrhel72le"
     TOPDIR=/root/HTX
5. make clean
6. make all
7. make tar

sucessfully got htx_package.tar.gz, the compilating process has some warnings but no errors.
To install:
1. tar xvf htx_package.tar.gz
2. cd htx_package
2. ./install -f

To run:
1.  su - htx 
2.  htx 
bash: htx: command not found...

**Comment by mehuljpatel** [comment]
Looks like htx_env.sh script is not running the way intended. On your setup, just edit /usr/lpp/htx/.bash_profile and add "." and space before /usr/lpp/htx/etc/scripts/htx_setup.sh. I will drop this change.

Alternatively, you can run htxscreen directly after installing HTX. (no su - htx and htx). Infact, thats the new way of running HTX and we will eventually sunset (su - htx and htx way of running).

**Comment by mehuljpatel** [comment]
Sorry, I mean HTX env is not getting set properly since /usr/lpp/htx/etc/scripts/htx_setup.sh is not running appropriately.

**Comment by mehuljpatel** [comment]
Done a code change in packaging/installer.sh file which was overwritting .bash_profile. Pl check out again.
