### ISSUE TITLE
Bug in installer.sh with "os_build" file.

### ISSUE THREAD

**Issue by dougmill-ibm** [open-power/HTX#111]
There is a problem with installer.sh (or the producer of the "os_build" file) whereby the installation has issues.  The error observed is
```
...
Your Install System:
Distro:RedHat
Arch:ppc64le
cat: os_build: No such file or directory
...
```
Which comes from line 88 of installer.sh:
```
if [[ $CURRENT_OS != $(cat os_build | grep Compiledon) ]];
```
It seems that either "os_build" was not created or else the CWD of the script is not correct to access it.

**Comment by rajashekhar1991** [comment]
"os_build" file will be generated once tarball is created ("make tar").  It contains the details of the machine on which project is built/compiled. 
Upon extracting the tar package, os_build file must be present in same directory as installer/uninstaller scripts. 
Please follow 1.3.1 section of "HTX User Manual" under "Documentation" section for the detailed steps in case you missed anything.

Please revert back if there is any issue.

Thanks, 
Raja

**Comment by dougmill-ibm** [comment]
I am not able to reproduce the "os_build" error. I will check with original user to see what might have been going on.
