### ISSUE TITLE
When run htx mdt.mem with the rule "hxemem64/default", it reports error: GLOBAL_ALLOC_MEM_PERCENT (invalid)

### ISSUE THREAD

**Issue by ping678** [open-power/HTX#112]
Steps to run:
1. modify mdt.mem
2. change the 2 lines as:
        reg_rules = "hxemem64/default"               * reg
        emc_rules = "hxemem64/default"               * emc
3. save the mdt.mem
4. run htx mdt.mem, choose 1 to active
5. choose 5 to check the mem status, it shows "ER".
6. choose 7  to view error log:
   /dev/mem          Jul 20 17:05:22 2017 err=00000000 sev=1 hxemem64
   line# 7 keywd = GLOBAL_ALLOC_MEM_PERCENT (invalid)
   /dev/mem          Jul 20 17:05:22 2017 err=00000000 sev=1 hxemem64
   Hardware Exerciser stopped on an error

**Comment by veereshj** [comment]
Rule files with default*  are enabled only for P9 and above architectures. 

If you wish to run with any of those rule files. Please also change executable to "hxemem64_new" in mdt. i.e
In mdt.mem, along with your changes also change the line as: 
HE_name = "hxemem64" ===> HE_name = "hxemem64_new"

**Comment by ping678** [comment]
Thank you veereshj! Seems I reported a fake bug, sorry! I didn't see that info in documents, maybe I missed something. I tried hxemem64_new as you said on a P8 system, it works.
