### ISSUE TITLE
Not able to add disk devices

### ISSUE THREAD

**Issue by jrziviani** [open-power/HTX#113]
Hi,

I tried to run
mdt_net mdt.io

Also tried to add manually in mdt.io
sdb:
        HE_name = "hxehd"                * Hardware Exerciser name, 14 char
        adapt_desc = "ide"               * adapter description, 11 char max.
        device_desc = "ide-vols"              * device description, 15 char max.
        reg_rules = "hxehd/default"      * reg
        emc_rules = "hxehd/default"      * emc
        cont_on_err = "NO"               * continue on error (YES/NO)

but I cannot run any test on my disk device. Maybe am I missing something in the docs.

Thanks

**Comment by jrziviani** [comment]
I also tried run it manually:

# hxestorage sdb REG ../rules/reg/hxestorage/default.hdd 
hxestorage for sdb: Error in hxfupdate function.
Unable to send message.
errno = 22: Invalid argument
hxestorage for sdb: Error in hxfupdate function.
Unable to access HTX message queue.
errno = 2: Invalid argument
data->htx_log_dir /tmp/

**Comment by mehuljpatel** [comment]
For manual execution. Please follow the steps below:
1. htxscreen -> start HTX
2. Drop to shell by choosing option 11
3. change dir to where hxestorage binary is and then run following command.
./hxestorage /dev/sdb OTH ../rules/reg/hxestorage/default.hdd

Lets know if you find any errors. 

While you tried to run the MDT (mdt.io), what was the HTX error msg. Can you share HTX error/msg logs here.

**Comment by jrziviani** [comment]
Hello!

Thanks for your support. My problem was: I was testing HTX on a QEMU/KVM guest that had a

`<target dev='vdb' bus='virtio'/>`

then, I changed that virtio to emulate scsi device and it worked perfectly.

`<target dev='sdb' bus='scsi'/>`

Thanks again!!
I'm closing this as not a bug.
