### ISSUE TITLE
Broken check for SMT

### ISSUE THREAD

**Issue by antonblanchard** [open-power/HTX#117]
HTX is looking for smt_snooze_delay in sysfs, which is no longer present:

```
        r1 = get_cmd_op(dest, "ls /sys/devices/system/cpu/cpu0 | grep smt_snooze_delay | wc -l");
        t->smt_enabled=atoi(dest);  /*System is smt capable and/or whether smt is enabled*/
```

If HTX wants to know if the box is currently in an SMT mode, then it should look at something like:

```
/sys/devices/system/cpu/cpu0/topology/thread_siblings
```

This will also tell you what SMT level it is in.

**Comment by vishnupriya-r99** [comment]
#118 has been pushed to counter this issue.  
smt_snooze_delay was used to find out some redundant information which is no longer necessary. Hence we're removing it.
 Currently we're counting the threads in each core whenever such information is requested.
