### ISSUE TITLE
No IO devices added into mdt file

### ISSUE THREAD

**Issue by davidzengxhsh** [open-power/HTX#119]
I build and installed the htx. But when I start htx by htxscreen, the hard disk is not added in the mdt.all or mdt.io.

[root@lpbriggs openpower]# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda           8:0    0  3.7T  0 disk
|-sda1        8:1    0    4M  0 part
|-sda2        8:2    0  500M  0 part /boot
`-sda3        8:3    0  3.7T  0 part
  |-ca-root 253:0    0   50G  0 lvm  /
  |-ca-swap 253:1    0    4G  0 lvm  [SWAP]
  `-ca-home 253:2    0  3.6T  0 lvm  /home
sdb           8:16   0  3.7T  0 disk
sdc           8:32   0  3.7T  0 disk

[root@lpbriggs openpower]# cat /usr/lpp/htx/mdt/mdt.io
default:
        HE_name = ""                                * Hardware Exerciser name, 14 char
        adapt_desc = ""                             * adapter description, 11 char max.
        device_desc = ""                            * device description, 15 char max.
        reg_rules = ""                              * reg rules
        emc_rules = ""                              * emc rules
        dma_chan = 0                                * DMA channel number
        idle_time = 0                               * idle time (secs)
        intrpt_lev = 0                              * interrupt level
        load_seq = 32768                            * load sequence (1 - 65535)
        max_run_tm = 7200                           * max run time (secs)
        port = "0"                                  * port number
        priority = 19                               * priority (1=highest to 19=lowest)
        slot = "0"                                  * slot number
        max_cycles = "0"                            * max cycles
        hft = 0                                     * hft number
        cont_on_err = "NO"                          * continue on error (YES/NO)
        halt_level = "1"                            * level <= which HE halts
        start_halted = "n"                          * exerciser halted at startup
        dup_device = "n"                            * duplicate the device
        log_vpd = "y"                               * Show detailed error log

There is no partition or OS installed on sdb and sdc. Any other restrictions for hard drive scanning?

**Comment by manishmukul** [comment]
Disks should be raw disk for HTX to pick it up for testing. Even if any filesystem ever existed on it, it will not be picked. 

Could you share "parted -mls" output here.

**Comment by davidzengxhsh** [comment]
[root@lpbriggs openpower]# parted -mls
BYT;
/dev/sda:4001GB:scsi:512:512:gpt:ATA ST4000NM0035-1V4:pmbr_boot;
1:1049kB:5243kB:4194kB:::prep;
2:5243kB:530MB:524MB:xfs::;
3:530MB:4001GB:4000GB:::lvm;

Error: /dev/sdb: unrecognised disk label
BYT;
/dev/sdb:4001GB:scsi:512:512:unknown:ATA ST4000NM0035-1V4:;

Error: /dev/sdc: unrecognised disk label
BYT;
/dev/sdc:4001GB:scsi:512:512:unknown:ATA ST4000NM0033-9ZM:;

BYT;
/dev/mapper/ca-home:3942GB:dm:512:512:loop:Linux device-mapper (linear):;
1:0.00B:3942GB:3942GB:xfs::;

BYT;
/dev/mapper/ca-swap:4295MB:dm:512:512:loop:Linux device-mapper (linear):;
1:0.00B:4295MB:4295MB:linux-swap(v1)::;

BYT;
/dev/mapper/ca-root:53.7GB:dm:512:512:loop:Linux device-mapper (linear):;
1:0.00B:53.7GB:53.7GB:xfs::;


/dev/sdb is added into mdt.io but sdc not.

**Comment by preeti-dhir** [comment]
Can you provide /tmp/part.pl.log file to look into.

**Comment by davidzengxhsh** [comment]
[part.pl.log](https://github.com/open-power/HTX/files/1574711/part.pl.log)

device=/dev/sdc of type="ddf_raid_member"  Detected !! 

I think this is the problem! But I have written this disk using fio.

**Comment by mehuljpatel** [comment]
sdc being a RAID member would not be touched by HTX. I think, fio is a file system based test program and hence it would create a file system on the device. 
If you are very sure about testing specific device, you can manually add entry into mdt file and run HTX. Once you run HTX storage exerciser, it will overwrite LBA 0 and later, HTX setup would pick it up for testing automatically.
