### ISSUE TITLE
Build: Fails with udat.h missing

### ISSUE THREAD

**Issue by fhaverkamp** [open-power/HTX#14]
haver@tul2eth3:~/HTX$ make 
...
making dir - /home/haver/HTX//install/ppc64le//usr/lpp/htx//bin/
/bin/mkdir -p /home/haver/HTX//install/ppc64le//usr/lpp/htx//bin/
make -C hxedapl
make[2]: Entering directory '/home/haver/HTX/bin/hxedapl'
/usr/bin/gcc -m64 -D__HTX_LINUX__ -DTRUE=1 -DFALSE=0 -D__64BIT__ -D__HTX_LE__ -D__RDMA_SUPPORTED__ -D__HTX_LINUX__ -D_64BIT_  -I./ -I/usr/include/ -I/home/haver/HTX//export/ppc64le//include/ -c ../hxecom/hxecom.c -o hxecom.o
In file included from ../hxecom/hxecomdef.h:64:0,
                 from ../hxecom/hxecom.c:94:
../hxecom/global.h:55:23: fatal error: dat2/udat.h: No such file or directory
compilation terminated.
Makefile:32: recipe for target 'hxecom.o' failed
make[2]: *** [hxecom.o] Error 1
make[2]: Leaving directory '/home/haver/HTX/bin/hxedapl'
Makefile:19: recipe for target 'hxedapl' failed
make[1]: *** [hxedapl] Error 2
make[1]: Leaving directory '/home/haver/HTX/bin'
Makefile:22: recipe for target 'bin' failed
make: *** [bin] Error 2
haver@tul2eth3:~/HTX$ find -name "udat.h"
haver@tul2eth3:~/HTX$

**Comment by maddy-kerneldev** [comment]
This got resolved for me with this package install "dapl-devel"

**Comment by fhaverkamp** [comment]
sudo apt-get install libdapl-dev yes, it worked.
