### ISSUE TITLE
With fast reboot and bootme, 20 second sleep before starting is significant

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/HTX#45]
Using an experimental firmware build and NVMe, the reboot cycle is down to around 35 seconds (to userspace in Ubuntu). When testing this with HTX bootme, the "Autostart is ON. Sleeping for 20 seconds and then calling runsup." becomes a significant amount of time in a bootme cycle designed to stress reboot code paths.

Suggestion: waive 20 seconds, start immediately.

Note that with Tuleta we had a memory corruption bug that may have been caught if tests were started quicker after boot, so a 20 second delay could end up hiding real bugs.

**Comment by mehuljpatel** [comment]
In etc/scripts/htx_setup.sh script there is 120 secs delay in case of bootme. This was mainly due ot race condition situations found in lab where HTX would kick start exers but underneath kernel/OS setup may still be in progress. So to avoid race condition, this delay was introduced.

# Work-around for autostartup problems
  if [ -f ${HTXLPP}.autostart ];
  then
     print_htx_log "Autostart is ON. Sleeping for 20 seconds and then calling runsup."
     sleep 20
     ${HTXSCRIPTS}runsup
  fi

 if [ -f ${HTXLPP}.autostart ] && [ -f $HTX_LOG_PATH/mpath_parts ] ; then
    if [ `cat $HTX_LOG_PATH/mpath_parts | wc -l` != 0 ] ; then
    htx_print_log "sleeping 120 seconds for bootme with multipath"
    sleep 120
    fi
  fi

**Comment by stewart-ibm** [comment]
I just deleted the delay: seems to work fine!

**Comment by mehuljpatel** [comment]
We need to keep this delay in place to avoid race condition issues in lab. So would close this issue in as-is state. For aggressive reboots, the delay can be manually removed from htx_setup.sh (as you did :)).

**Comment by stewart-ibm** [comment]
The race conditions *should* be solvable by other means... e.g. have the correct dependencies before starting HTX, say through systemd rather than just logging in.
