### ISSUE TITLE
bootme interval of 5 minutes doesn't seem to ever run HTX

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/HTX#46]
I set BOOTME to go every five minutes:
REBOOT: 0,5,10,15,20,25,30,35,40,45,50,55 *

yet I never see the big HTX in that cycle, I just get a constant reboot.

With my experimental firmware build where reboot-to-ubuntu-and-htx is around 35 seconds, a 5 minute cycle is a reasonable time.

**Comment by mehuljpatel** [comment]
Duplicate of issue #45
