### ISSUE TITLE
htx user doesn't set PATH to source shell scripts correctly

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/HTX#47]
Fresh ubuntu 16.04 install on ppc64el

building HTX according to README.md (and installing Ubuntu package) and then going "su - htx" gives errors of being able to source htx_env.sh. This was fixed by adding "PATH=$PATH:./etc/scripts/" to the htx user .bash_profile before the sourcing of the HTX stuff.

i.e. out of the box, HTX doesn't set itself up correctly.

**Comment by mehuljpatel** [comment]
I see a problem that etc/scripts/htx_env.sh invocation from etc/scripts/htx_setup.sh is missing absolute path. This will be fixed.

**Comment by mehuljpatel** [comment]
Pull request #48 has been merged to address this issue. Closing this one.
