### ISSUE TITLE
HTX home directory is in odd place

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/HTX#50]
The whole htx user being a user you have a login shell for is rather strange and unconventional.

Additionally, having a user home dir in /usr throws warnings from `lintian`

```
W: htxubuntu: file-in-unusual-dir usr/lpp/htx/.bashrc
```

**Comment by mehuljpatel** [comment]
Agree, its unconventional. We are working on couple of things that will remove this concern. 1) need of separate user - htx. 2) making HTX relocatable from install/logging perspective.
HTX will run as user root only so there is no need to create separate user 'htx' and all related issues will be removed.
Regarding the relocation of HTX package, the idea is to keep anchor point of HTX install in /var/log/htx_install_path immediately after installation and all HTX binaries/scripts would derive HTX paths from this anchor point.

**Comment by mehuljpatel** [comment]
HTX has support for creating tarball with installer. This installer allows to install HTX at any specified location. 
I think, this issue can be closed now.
