### ISSUE TITLE
Compile instructions are incorrect

### ISSUE THREAD

**Issue by aik** [open-power/HTX#51]
README.md says:
cd into dapl directory and "./configure" "make" and then "make install" 

"find" says there is no such directory.

**Comment by aik** [comment]
"make all" works in root directory, "make install" does not work, "make dev" does. I wish I could know what exactly is needed to run the test suite and if there is a way to avoid installing in /usr/.

**Comment by aik** [comment]
The created deb package does not create an "htx" user so how to run the test suite - is absolutely unclear :-/

**Comment by williamspatrick** [comment]
If you do not have a dapl directory, you did not follow the instructions.  The instructions explicitly say to download something.

**Comment by aik** [comment]
Ubuntu 16 has libdapl-dev which means I do not have to download a thing, do not I?

**Comment by aik** [comment]
I can create another issue with the exact same content if required (as this one is marked "closed" while it apparently is not solved), should I?

**Comment by williamspatrick** [comment]
I think you are just misreading the documentation. Steps 3.1,3.2,3.3 are only required on Ubuntu 14.04. If you already have libdapl, you don't need to do them.

**Comment by aik** [comment]
Step 3 says "apt-get install gcc make libncurses5 g++ libdapl-dev" and apparently it is needed to compile htx, not just dapl. So I assume the step 3 is necessary whether it is 14.04 or not. And 14.04 is is only mentioned in 3.1 so I assumed that 3.2 and 3.3 are needed for every ubuntu. I have no idea what dapl is so I can also expect that lets say makefile will clone it locally or something like this and compile it. May be "dapl" is a test engine itself, and I do have to compile it no matter what, do I really have to google it?... And I just see step 1 installs only git but not gcc and step 3 installs gcc and why it is not in step 1 - I do not understand.

What I am saying is that  README.md could be structured better. You apparently disagree, ok.

**Comment by williamspatrick** [comment]
@aik - No, I agree that README could be phrased better now that I understand the problem.  Your initial problem report could have included much more details on the steps you took to "produce" this and what system you were running on.

**Comment by williamspatrick** [comment]
@manishmukul - Please look at the phrasing of steps 3.1 thru 3.3.  As @aik points out those are only necessary for Ubuntu 14, but the current wording makes it not obvious if 3.2 and 3.3 should be ran all the time or only for Ubuntu 14.

**Comment by aik** [comment]
libncurses5-dev also needs to be installed

**Comment by manishmukul** [comment]
Sure, we can look at rephrasing readme. But making 3.2 and 3.3 bullets specific to ubuntu 14.04 would not be correct. We have couple of test systems running ubuntu 16.04 

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

and there libdapl-dev is not installed by default. I am not sure if it varies from flavor to flavor but its required for ubuntu 16.04 as well in some cases. We will add a note that these steps are not required if libdapl-dev is already installed.

**Comment by aik** [comment]
not installed != not available from repo. 3.2 and 3.3 are telling about building dapl while it can just be  installed. Or I am missing the point.
