### ISSUE TITLE
Missing many, many tests

### ISSUE THREAD

**Issue by aik** [open-power/HTX#52]
Compared to internally available htxubuntu-409.deb. Please fix it. Thanks.

**Comment by aik** [comment]
For example: net.mdt

**Comment by williamspatrick** [comment]
Are you sure this isn't intentional?  I don't know where "internal" is, but some vendors might choose to put their own proprietary tests into their own HTX distribution.

**Comment by mehuljpatel** [comment]
net.mdt is supported on Open HTX. One would see device entries in net.mdt only if networks are configured.

**Comment by aik** [comment]
hm. correct, sorry for disturbance.
