### ISSUE TITLE
Missing /usr/lpp/htx/ecg/

### ISSUE THREAD

**Issue by aik** [open-power/HTX#59]
I compiled htx, built and installed the deb package.
Then "su - htx", "build_net help", "htx", "net.mdt" and started the test which stopped immediately with:

htx_messages      Sep 23 20:32:21 2016 err=00000000 sev=1 hxssup
hxecom HE program for enp0s5 terminated by signal 9.

After a closer look to build_net's output, I noticed a warning about missing  /usr/lpp/htx/ecg/ (no idea what it is and what it is for) but I created this directory, repeated all the steps and it works now. Would be nice to have this fixed in HTX

**Comment by shilpac1** [comment]
I too compiled HTX and installed package in our local test machine and noticed that network exerciser is running OK. Please look into the logs below. 

 "cp: cannot create regular file '/usr/lpp/htx//ecg//net.ecg': No such file or directory" - I believe this warning has nothing to do with the error what you have observed.

Let me know if you have followed any other steps.

Logs
===

====

(0) htx @ fr70p01: /usr/lpp/htx
# build_net help y y
Your host com_dev for comname fr70p01 is set to enP3p3s0f0, netmask=255.255.255.0
Creating profile template... /usr/lpp/htx//bpt
onesys=y
Automation script will now try to detect your network topology.
In case of errors manually edit bpt file and run build_net bpt to setup hxecom networks
Running command ..
 /usr/lpp/htx//bin//auto  enP3p3s0f1 enP3p3s0f2 enP3p3s0f3
Your host com_dev for comname fr70p01 is set to enP3p3s0f0, netmask=255.255.255.0
Your network setup looks like ....
 enP3p3s0f1 -> enP3p3s0f2

A real system somewhere on the network is configured with net_id=100. Skipping 100 net_id ....
A real system somewhere on the network is configured with net_id=101. Skipping 101 net_id ....
A real system somewhere on the network is configured with net_id=102. Skipping 102 net_id ....
Running build_net bpt to configure test networks ....
Your host com_dev for comname fr70p01 is set to enP3p3s0f0, netmask=255.255.255.0
Running Linux version of build_net.
...............................Found enP3p3s0f0 in location N/A
enP3p3s0f0.. Detected site network. Skipping it .... .
...............................Found enP3p3s0f1 in location N/A
...............................Found enP3p3s0f2 in location N/A
...............................Found enP3p3s0f3 in location N/A
Configuring Unknown, dev=enP3p3s0f1, rule=103net, hostname=103net24,ip address=103.1.1.24
Configuring Unknown, dev=enP3p3s0f2, rule=103nets, hostname=103nets24,ip address=103.1.2.24

cp: cannot create regular file '/usr/lpp/htx//ecg//net.ecg': No such file or directory
Ping network 103.1.1.24 from dev enP3p3s0f2---->OK
Ping network 103.1.2.24 from dev enP3p3s0f1---->OK
All networks ping Ok

(0) htx @ fr70p01: /usr/lpp/htx

with mdt.bu


Enter the desired mdt test file to copy to "mdt".
mdt.bu
Do you want to run save.default, which formats and compresses log files (y)?
y
Preparing hxecom environment...
Preparing FPU environment...
Preparing CPU environment...
Preparing hxemem64 environment...
/usr/lpp/htx/bin
               HTX Device Status Summary  Current Time: 271  09/27/16  23:43:57
Cycle Count(Min/Max)=2/50            System Start Time: 271  09/27/16  23:34:48
Page Number(Cur/Max)=1/4
--------------------------------------------------------------------------------
            Last Update   Cycle Curr.   |             Last Update   Cycle Curr.
ST Device   Day   Time    Count Stanza  | ST Device   Day   Time    Count Stanza
RN cache0   271 23:43:56       11    4  | RN cpu15    271 23:43:50        3    1
RN cache1   271 23:43:54        9    4  | RN cpu16    271 23:43:48        3    2
RN cpu0     271 23:43:53        3    3  | RN cpu17    271 23:43:49        3    3
RN cpu1     271 23:43:52        3    4  | RN cpu18    271 23:43:11        2   12
RN cpu2     271 23:43:51        3    2  | RN cpu19    271 23:43:42        3    2
RN cpu3     271 23:43:55        3    5  | RN enP3p3s0f271 23:43:57       50    1
RN cpu4     271 23:43:46        3    2  | RN enP3p3s0f271 23:43:57       50    1
RN cpu5     271 23:43:55        3    4  | RN fpu0     271 23:43:55        4   14
RN cpu6     271 23:43:07        2   12  | RN fpu1     271 23:43:57        4   15
RN cpu7     271 23:43:53        3    6  | RN fpu2     271 23:43:57        4   10
RN cpu8     271 23:43:54        3    3  | RN fpu3     271 23:43:55        4   19
RN cpu9     271 23:43:55        3    4  | RN fpu4     271 23:43:55        4    8
RN cpu10    271 23:43:14        2   12  | RN fpu5     271 23:43:55        4   18
RN cpu11    271 23:43:43        2   11  | RN fpu6     271 23:43:53        4    9
RN cpu12    271 23:43:49        3    2  | RN fpu7     271 23:43:52        4   23
RN cpu13    271 23:43:54        3    4  | RN fpu8     271 23:43:53        4   18
RN cpu14    271 23:43:53        3    4  | RN fpu9     271 23:43:53        4   18


with net.mdt

Enter the desired mdt test file to copy to "mdt".
net.mdt
Do you want to run save.default, which formats and compresses log files (y)?
y
Preparing hxecom environment...


                                        |
                                        |
                                        |
               HTX Device Status Summary  Current Time: 271  09/27/16  23:47:37
Cycle Count(Min/Max)=0/6             System Start Time: 271  09/27/16  23:45:57
Page Number(Cur/Max)=1/1
--------------------------------------------------------------------------------
            Last Update   Cycle Curr.   |             Last Update   Cycle Curr.
ST Device   Day   Time    Count Stanza  | ST Device   Day   Time    Count Stanza
RN enP3p3s0f271 23:47:31        5    1  |
RN enP3p3s0f271 23:47:31        6    1  |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |
                                        |

**Comment by manishmukul** [comment]
Hi Alexey,
We are not able to reproduce reported issue of exerciser terminating on our local machine.
If you see this issue again, could you please share following files so that we could find out whats going wrong.
- /tmp/htxerr
- /tmp/htxmsg
- /tmp/build_net*
- /etc/hosts
- ip addr show command output
- /usr/lpp/htx/bpt file content

The other issue of missing net.ecg is benign and can be ignored. We will be removing the error message soon. 

Thanks,
Manish

**Comment by manishmukul** [comment]
Please reopen if you still see this problem with above contents attached.
