### ISSUE TITLE
Compile failed under Ubuntu 16.04

### ISSUE THREAD

**Issue by mabo0105** [open-power/HTX#86]
I got this issue after doing "make all"

https://drive.google.com/open?id=0BxCL03QM3OEGTVNENFc0R18yZkk

And below link is makelog

https://drive.google.com/open?id=0BxCL03QM3OEGN203SV9LSnhWaWs

I did set the TOPDIR to where the HTX folder is 

But have no idea how to solve this issue

Hope can get help soon

Thank you

**Comment by williamspatrick** [comment]
Are you compiling this on an x86 machine?  This is POwER code. You probably need a cross compiler set up.

**Comment by mehuljpatel** [comment]
I tried on ppc64 linux box and it compiled fine. Are you trying to compile it on x86 box ?

**Comment by mehuljpatel** [comment]
Hope you had a chance to compile code on POWER linux box. Closing the issue.
