### ISSUE TITLE
Installing htx on redhat

### ISSUE THREAD

**Issue by kpooja88** [open-power/HTX#93]
Hi,

I am trying to install HTX on redhat 7.3, in the readme file, I see:
"To make rpm package: work in progress"
What are the steps to install on RH?

I was successfully able to install on Ubuntu, and I followed the same steps for RedHat, but unlike Ubuntu where I can do a 'make-deb', how do I proceed on RH?

**Comment by mehuljpatel** [comment]
Hi Pooja, a work is in progress to create HTX tarball with HTX binaries + installer. It should be updated here in few days.

**Comment by mehuljpatel** [comment]
HTX build now supports creating tarball (make all; make tar;) with HTX installer script. Please refer top level README for building instructions and Documentation/HTX_user_manual.txt for installation instructions.
